# Generated by Django 4.0.6 on 2022-08-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishapi', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='rating',
        ),
    ]
